### ISSUE TITLE
Request : Add support for multiple Frame TV

### ISSUE THREAD

**Issue by djfjeff** [vivalatech/homeassistant-addons#2]
Hi,

I have 2 Frame TV in my home and that would be perfect if your addon can support uploading art to both of them. Maybe just specify a comma separated list of Frame IP address would be enough.

Thanks!

**Comment by vivalatech** [comment]
It's now possible to add multiple Frame TV IP's comma separated, also there is a "Use Same Image" option to control the behaviour in case multiple IP's are specified, when enabled it will upload the same image to all TV's, when disabled it will get a different image for each TV.

**Comment by djfjeff** [comment]
Thanks a lot, tested and working fine with 2 Frame TV and same image!
